name: frontend
description: Flutter app for Crewmeister coding challenge
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  retrofit: ^4.1.0
  universal_html: ^2.2.4

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  retrofit_generator: ^8.1.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
